version: "3.3"
services:
#Proxy server
  proxy:
    build: ./proxy
    environment:
      PROXY_HOST: "0.0.0.0"
      PROXY_PORT: "5433"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
    ports:
      - "5433:5433"
    volumes:
      - "../:/code"
# Database
  postgres:
    image: postgres:13.3
    command:
      - "postgres"
      - "-c"
      - "max_connections=1000"
    environment:
      POSTGRES_DB: "benchmark"
      POSTGRES_USER: "benchmark"
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"
# Benchmark
  benchmark:
    build: ./benchmark
    depends_on:
      - proxy
      - postgres
    environment:
      PROXY_HOST: "proxy"
      PROXY_PORT: "5433"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_USER: "benchmark"
      POSTGRES_DB: "benchmark"
      POSTGRES_PASSWORD: "1234"
      CLIENTS: 10
      TIME_SEC: 30
      THREADS: 10